var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(l){var n=0;return function(){return n<l.length?{done:!1,value:l[n++]}:{done:!0}}};$jscomp.arrayIterator=function(l){return{next:$jscomp.arrayIteratorImpl(l)}};$jscomp.makeIterator=function(l){var n="undefined"!=typeof Symbol&&Symbol.iterator&&l[Symbol.iterator];return n?n.call(l):$jscomp.arrayIterator(l)};$jscomp.arrayFromIterator=function(l){for(var n,t=[];!(n=l.next()).done;)t.push(n.value);return t};
$jscomp.arrayFromIterable=function(l){return l instanceof Array?l:$jscomp.arrayFromIterator($jscomp.makeIterator(l))};
PROJECT.APP=function(l){function n(){var a=this;a.xmlhttp=function(){try{var a=new ActiveXObject("Msxml2.XMLHTTP")}catch(d){try{a=new ActiveXObject("Microsoft.XMLHTTP")}catch(e){a=!1}}a||"undefined"==typeof XMLHttpRequest||(a=new XMLHttpRequest);return a}();a.on_back=null;a.active=!1;a.xmlhttp.onreadystatechange=function(b){if(4==a.xmlhttp.readyState&&200==a.xmlhttp.status){b=a.xmlhttp.responseText;if(null!=a.on_back)a.on_back(b);a.on_back=null;a.active=!1}};a.save=function(b,d,e,f){a.on_back=f;a.xmlhttp.open("POST",
b,!0);a.xmlhttp.setRequestHeader("Content-type","application/x-www-form-urlencoded");a.xmlhttp.send("data="+e+"&info="+d);a.active=!0};a.load=function(b,d){a.active=!0;a.on_back=d;a.xmlhttp.open("GET",b,!0);a.xmlhttp.send(null)}}function t(){for(var a=0;a<r.length&&r[a].active;a++);if(a<r.length)return r[a];r.push(new n);return r[a]}function I(){null!==this.parent&&this.parent.remove(this);for(this.parent=null;0<this.children.length;)this.remove(this.children[0]);for(;0<this.avk.img.length;){var a=
this.avk.img.pop();a.geometry.dispose();a.material.dispose();a.material.map.dispose();a.material.map=null;a.material=null;a.geometry=null}}function v(a){this.remove(a)}function w(a){0<=a&&a<this.children.length&&this.remove(this.children[a])}function x(a){this.add(a);this.orderRefresh();a.alpha=a.alpha}function y(a){if(a===this)return console.error("THREE.Object3D.add: object can't be added as a child of itself.",a),this;if(a&&a.isObject3D){null!==a.parent&&a.parent.remove(a);a.parent=this;a.dispatchEvent({type:"added"});
var b=null;this.avk&&this.children[0]==this.avk.img[this.avk.currentFrame]&&(b=this.children.shift());this.children.unshift(a);b&&this.children.unshift(b);this.orderRefresh();a.alpha=a.alpha}else console.error("THREE.Object3D.add: object not an instance of THREE.Object3D.",a)}function z(){for(var b=0;b<this.children.length;b++)this.children[b].renderOrder=this.renderOrder+(b+1)*this.renderOrderStep,this.children[b].renderOrderStep=this.renderOrderStep/a.order_step,this.children[b].orderRefresh&&this.children[b].orderRefresh()}
function A(){for(var a={x:this.x,y:this.y},c=this.parent;null!=c;)a.x+=c.x,a.y+=c.y,c=c.parent;return a}function J(b){b.preload();a.obj_loader.setMaterials(b);a.obj_loader.load(PROJECT.DAT.object+".obj"+a.ver,function(b){a.objects=b;a.objects_stack={}})}function K(b){var c=this;c.name=b;a.sounds[b]={data:null};a.audioLoader.load(PROJECT.DAT.snd_folder+b+".mp3",function(b){var d=new THREE.Audio(B);a.sounds[c.name]=d;d.setBuffer(b);d.setLoop(!1);d.setVolume(.5)})}function L(b){var c=this;c.name=b;a.fbx_loader.load(PROJECT.DAT.fbx_folder+
b+".fbx"+a.ver,function(b){a.fbx[c.name]=b})}function M(b){var c=this;c.name=b;a.atlases[b]={material:null,map:null};a.loader.load(PROJECT.DAT.gfx_gui_folder+b+".png",function(b){a.atlases[c.name].material=b});a.file_loader.load(PROJECT.DAT.assets[b],function(b){a.atlases[c.name].map=JSON.parse(b)})}function N(b,c){for(var d in c.children){b[d]={name:c.children[d].name,type:c.children[d].type,x:c.children[d].x,y:c.children[d].y,w:c.children[d].w,h:c.children[d].h,properties:{},col:c.children[d].col?
c.children[d].col:0,pic:c.children[d].pic,children:{},copy:function(b,c){return a.get_copy(this,b,c)}};for(var e in c.children[d].properties)b[d].properties[e]=c.children[d].properties[e]}}function C(b){for(var c in b.children)a.custom_types[b.children[c].type]&&0==Object.keys(b.children[c].children).length&&N(b.children[c].children,a.custom_types[b.children[c].type]),C(b.children[c])}function D(b,c){for(var d=0;d<c.length;d++){var e=c[d];b.children[e.name]={name:e.name,type:e.type,x:e.x,y:e.y,w:e.w,
h:e.h,properties:{},col:e.col?e.col:0,pic:e.pic?e.pic:"",children:{},copy:function(b,c){return a.get_copy(this,b,c)}};for(var f=0;f<e.properties.length;f++)b.children[e.name].properties[e.properties[f].name]=e.properties[f].val;0<e.groups.length&&(D(b.children[e.name],e.groups),a.custom_types[e.type]=b.children[e.name])}}function O(){for(var b=0;b<PROJECT.GUI.length;b++){var c=PROJECT.GUI[b];PROJECT.WND[c.name]={name:c.name,type:"wnd",x:0,y:0,w:PROJECT.DAT.width,h:PROJECT.DAT.height,properties:{},
pic:"",children:{},copy:function(b,c){return a.get_copy(this,b,c)}};D(PROJECT.WND[c.name],c.groups)}for(b=0;b<PROJECT.GUI.length;b++)C(PROJECT.WND[PROJECT.GUI[b].name])}function E(b){b.stopPropagation();b.preventDefault();b.touches&&0<b.touches.length&&(b=b.touches[0]);var c=Math.floor(b.pageX/a.scale-a.dx);b=Math.floor(b.pageY/a.scale-a.dy);var d=a.get_target(a.gui_gfx,c,b,1,1);if(d){if(a.down_object&&a.down_object!=d){if(a.down_object.avk.on_out)a.down_object.avk.on_out(a.down_object,c,b);a.down_object=
null}if(d.avk.on_move)d.avk.on_move(d,c,b)}}function F(b){b.stopPropagation();b.preventDefault();b.touches&&0<b.touches.length&&(b=b.touches[0]);var c=Math.floor(b.pageX/a.scale-a.dx);b=Math.floor(b.pageY/a.scale-a.dy);var d=a.get_target(a.gui_gfx,c,b,1,1);if(d&&(a.down_object=d,d.avk.on_down))d.avk.on_down(d,c,b)}function u(b){b.stopPropagation();b.preventDefault();b.changedTouches&&0<b.changedTouches.length&&(b=b.changedTouches[0]);var c=Math.floor(b.pageX/a.scale-a.dx);b=Math.floor(b.pageY/a.scale-
a.dy);var d=a.get_target(a.gui_gfx,c,b,1,1);if(d){if(a.down_object==d&&a.down_object.avk.on_click&&0==a.busy)a.down_object.avk.on_click(d,c,b);a.down_object=null;if(d.avk.on_up)d.avk.on_up(d,c,b)}else if(a.down_object){if(a.down_object.avk.on_out)a.down_object.avk.on_out(a.down_object,c,b);a.down_object=null}}var a=this,k=[];a.order_step=1E3;a.on_start=l;a.on_resize_functions=[];a.on_update_functions=[];a.custom_types={};a.busy=0;a.on_first_click=null;a.ver="?ver="+PROJECT.STR.gfx_version;a.up_gui=
!0;var r=[];a.save=function(a,c,d,e){t().save(a,c,d,e)};a.load=function(a,c){t().load(a,c)};a.isMobile={Android:function(){return navigator.userAgent.match(/Android/i)},BlackBerry:function(){return navigator.userAgent.match(/BlackBerry/i)},iOS:function(){return navigator.userAgent.match(/iPhone|iPad|iPod/i)},Opera:function(){return navigator.userAgent.match(/Opera Mini/i)},Windows:function(){return navigator.userAgent.match(/IEMobile/i)},any:function(){return a.isMobile.Android()||a.isMobile.BlackBerry()||
a.isMobile.iOS()||a.isMobile.Opera()||a.isMobile.Windows()}};a.dist=PROJECT.DAT.height/2/Math.tan(Math.PI*PROJECT.DAT.angle/360);a.scene=new THREE.Scene;a.scene_3d=new THREE.Scene;a.scene_3d.fog=new THREE.Fog(8708347,.015,350);a.camera=new THREE.PerspectiveCamera(PROJECT.DAT.angle,PROJECT.DAT.width/PROJECT.DAT.height,.1,1E7);a.camera_3d=new THREE.PerspectiveCamera(PROJECT.DAT.angle,PROJECT.DAT.width/PROJECT.DAT.height,.1,1E7);var B=new THREE.AudioListener;a.camera.add(B);a.camera_3d.position.z=475;
a.camera_3d.position.y=422;a.camera_3d.position.x=0;a.camera_3d.rotation.x=30*-Math.PI/180;a.camera.position.z=0;a.camera.rotation.z=Math.PI;a.camera.rotation.y=Math.PI;a.renderer=new THREE.WebGLRenderer;a.renderer.autoClear=!1;a.renderer.setClearColor(PROJECT.DAT.color);a.renderer.setSize(PROJECT.DAT.width,PROJECT.DAT.height);document.getElementById("game").appendChild(a.renderer.domElement);a.renderer.domElement.style.position="absolute";a.renderer.domElement.style["z-index"]="1";a.app_gfx=new THREE.Group;
a.preloader_gfx=new THREE.Group;a.msg_up_gfx=new THREE.Group;a.msg_shadow_gfx=new THREE.Group;a.msg_down_gfx=new THREE.Group;a.middle_gfx=new THREE.Group;a.gui_gfx=new THREE.Group;a.scene_3d.add(a.app_gfx);a.scene.add(a.gui_gfx);a.gui_gfx.position.z=a.dist;a.gui_gfx.position.x=-PROJECT.DAT.width/2;a.gui_gfx.position.y=-PROJECT.DAT.height/2;a.middle_gfx.interactive=!1;a.msg_down_gfx.interactive=!1;a.msg_shadow_gfx.interactive=!1;a.msg_up_gfx.interactive=!1;a.preloader_gfx.interactive=!1;a.middle_gfx.avk=
{img:[]};a.msg_down_gfx.avk={img:[]};a.msg_shadow_gfx.avk={img:[]};a.msg_up_gfx.avk={img:[]};a.preloader_gfx.avk={img:[]};a.gui_gfx.add(a.middle_gfx);a.gui_gfx.add(a.msg_down_gfx);a.gui_gfx.add(a.msg_shadow_gfx);a.gui_gfx.add(a.msg_up_gfx);a.gui_gfx.add(a.preloader_gfx);a.middle_gfx.renderOrder=1E15;a.msg_down_gfx.renderOrder=2E15;a.msg_shadow_gfx.renderOrder=3E15;a.msg_up_gfx.renderOrder=4E15;a.preloader_gfx.renderOrder=5E15;a.middle_gfx.renderOrderStep=1E15/a.order_step;a.msg_down_gfx.renderOrderStep=
2E15/a.order_step;a.msg_shadow_gfx.renderOrderStep=3E15/a.order_step;a.msg_up_gfx.renderOrderStep=4E15/a.order_step;a.preloader_gfx.renderOrderStep=5E15/a.order_step;a.middle_gfx.addChild=a.msg_down_gfx.addChild=a.msg_shadow_gfx.addChild=a.msg_up_gfx.addChild=a.preloader_gfx.addChild=x;a.middle_gfx.addChildDown=a.msg_down_gfx.addChildDown=a.msg_shadow_gfx.addChildDown=a.msg_up_gfx.addChildDown=a.preloader_gfx.addChildDown=y;a.middle_gfx.removeChild=a.msg_down_gfx.removeChild=a.msg_shadow_gfx.removeChild=
a.msg_up_gfx.removeChild=a.preloader_gfx.removeChild=v;a.middle_gfx.removeChildDown=a.msg_down_gfx.removeChildDown=a.msg_shadow_gfx.removeChildDown=a.msg_up_gfx.removeChildDown=a.preloader_gfx.removeChildDown=w;a.middle_gfx.orderRefresh=a.msg_down_gfx.orderRefresh=a.msg_shadow_gfx.orderRefresh=a.msg_up_gfx.orderRefresh=a.preloader_gfx.orderRefresh=z;a.middle_gfx.getGlobalPosition=a.msg_down_gfx.getGlobalPosition=a.msg_shadow_gfx.getGlobalPosition=a.msg_up_gfx.getGlobalPosition=a.preloader_gfx.getGlobalPosition=
A;a.add_shadow=function(b){a.shadow=a.get_sprite(b);a.shadow.interactive=!0;a.shadow.sy=200;a.shadow.sx=a.width/8/a.scale;a.shadow.x=(PROJECT.DAT.width-a.width/a.scale)/2;a.shadow.p_w=a.shadow.avk.i_w;a.shadow.p_h=a.shadow.avk.i_h;a.msg_shadow_gfx.addChild(a.shadow);a.shadow.visible=!1};a.get_sprite=function(b,c){function d(b){b=new THREE.SpriteMaterial({map:a.materials[b],color:16777215,transparent:!0,sizeAttenuation:!1,depthWrite:!1,depthTest:!1});b=new THREE.Sprite(b);b.scale.set(b.material.map.image.width/
a.dist,b.material.map.image.height/a.dist,1);b.center.x=0;b.center.y=1;b.i_rw=b.i_w=b.material.map.image.width;b.i_rh=b.i_h=b.material.map.image.height;return b}function e(b){for(var c in a.atlases){var d=a.atlases[c];for(e in d.map.frames)if(e==b){b=new THREE.SpriteMaterial({map:d.material,color:16777215,transparent:!0,sizeAttenuation:!1,depthWrite:!1,depthTest:!1});d=d.map.frames[e];var f=b.map.image.width;c=b.map.image.height;b=new THREE.Sprite(b);var e=new THREE.BufferGeometry;var h=d.frame.x/
f,g=d.frame.y/c;f=(d.frame.x+d.frame.w)/f;c=(d.frame.y+d.frame.h)/c;c=new Float32Array([-.5,-.5,0,h,1-c,.5,-.5,0,f,1-c,.5,.5,0,f,1-g,-.5,.5,0,h,1-g]);c=new THREE.InterleavedBuffer(c,5);e.setIndex([0,1,2,0,2,3]);e.addAttribute("position",new THREE.InterleavedBufferAttribute(c,3,0,!1));e.addAttribute("uv",new THREE.InterleavedBufferAttribute(c,2,3,!1));b.geometry=e;b.i_rw=d.frame.w;b.i_rh=d.frame.h;b.i_w=d.spriteSourceSize.w;b.r_h=d.spriteSourceSize.h;b.scale.set(d.frame.w/a.dist,d.frame.h/a.dist,1);
b.center.x=0;b.center.y=1;b.position.x=d.spriteSourceSize.x;b.position.y=d.spriteSourceSize.y;return b}}return null}var f=new THREE.Group;f.avk={img:[],currentFrame:0};f.addChild=x;f.addChildDown=y;f.removeChild=v;f.removeChildDown=w;f.orderRefresh=z;f.destroy=I;f.getGlobalPosition=A;f.interactive=!1;if("undefined"==typeof b||""==b)f.avk.i_rw=f.avk.i_w=0,f.avk.i_rh=f.avk.i_h=0;else{if(c)if(Array.isArray(b))for(var h=0;h<b.length;h++)f.avk.img.push(e(b[h]));else f.avk.img.push(e(b));else if(Array.isArray(b))for(h=
0;h<b.length;h++)f.avk.img.push(d(b[h]));else f.avk.img.push(d(b));f.add(f.avk.img[0]);f.avk.i_rw=f.avk.img[0].i_rw;f.avk.i_w=f.avk.img[0].i_w;f.avk.i_rh=f.avk.img[0].i_rh;f.avk.i_h=f.avk.img[0].i_h}return f};Object.defineProperty(THREE.Object3D.prototype,"sx",{get:function(){"undefined"==typeof this._sx&&(this._sx=1);return this._sx},set:function(a){this._sx=a;0==this._sx&&(this._sx=1E-17);this.scale.set(this.sx,this.sy,1)}});Object.defineProperty(THREE.Object3D.prototype,"sy",{get:function(){"undefined"==
typeof this._sy&&(this._sy=1);return this._sy},set:function(a){this._sy=a;0==this._sy&&(this._sy=1E-17);this.scale.set(this.sx,this.sy,1)}});Object.defineProperty(THREE.Object3D.prototype,"alpha",{get:function(){"undefined"==typeof this._alpha&&(this._alpha=1);return this._alpha},set:function(a){this._alpha=a;if(this.avk){for(var b=this.parent;null!=b;)a*=b.alpha,b=b.parent;for(b=0;b<this.avk.img.length;b++)this.avk.img[b].material.opacity=a;for(b=0;b<this.children.length;b++)this.children[b].avk&&
(this.children[b].alpha=this.children[b].alpha)}}});Object.defineProperty(THREE.Object3D.prototype,"x",{get:function(){return this.position.x},set:function(a){this.position.x=a}});Object.defineProperty(THREE.Object3D.prototype,"y",{get:function(){return this.position.y},set:function(a){this.position.y=a}});Object.defineProperty(THREE.Object3D.prototype,"text",{get:function(){return this.avk&&this.avk.txt?this.avk.txt.text:null},set:function(a){this.avk&&this.avk.txt&&(this.avk.txt.text=a)}});a.loading_step=
0;a.materials={};a.atlases={};a.manager=new THREE.LoadingManager;a.loader=new THREE.TextureLoader(a.manager);a.font_loader=new THREE.FontLoader(a.manager);a.file_loader=new THREE.FileLoader(a.manager);a.obj_loader=new THREE.OBJLoader(a.manager);a.mtl_loader=new THREE.MTLLoader(a.manager);a.fbx_loader=new THREE.FBXLoader(a.manager);a.audioLoader=new THREE.AudioLoader(a.manager);a.manager.onStart=function(a,c,d){};a.manager.onProgress=function(b,c,d){0<a.loading_step&&PROJECT.PRELOADER.set_progress(c/
d)};a.manager.onError=function(a){console.log("loading error:"+a)};a.get_text=function(a,c,d){a=new THREE_Text2D.SpriteText2D(a,{align:THREE_Text2D.textAlign.center,font:c+"px "+PROJECT.STR.font_name,fillStyle:d,antialias:!0});a.material.map.magFilter=THREE.NearestFilter;a.material.map.minFilter=THREE.NearestFilter;return a};a.get_text_3d=function(b,c,d){var e=new THREE.TextGeometry(b,{font:a.font,size:c,height:0,curveSegments:12,bevelEnabled:!0,bevelThickness:0,bevelSize:0,bevelOffset:0,bevelSegments:0});
d=new THREE.MeshBasicMaterial({color:d,opacity:1,transparent:!0,depthWrite:!1,depthTest:!1});e=(new THREE.BufferGeometry).fromGeometry(e);e=new THREE.Mesh(e,d);e.position.x=0;e.position.y=c;e.position.z=0;e.rotation.x=0;e.rotation.y=Math.PI;e.rotation.z=Math.PI;e.text=b;e.font_size=c;e.set_text=function(b){this.text!=b&&(this.text=b,this.geometry.dispose(),b=new THREE.TextGeometry(b,{font:a.font,size:this.font_size,height:0,curveSegments:12,bevelEnabled:!0,bevelThickness:0,bevelSize:0,bevelOffset:0,
bevelSegments:0}),this.geometry=(new THREE.BufferGeometry).fromGeometry(b))};return e};a.get_plane=function(b){a.objects_stack[b]||(a.objects_stack[b]=[]);for(var c=0;c<a.objects_stack[b].length;c++)if(!a.objects_stack[b][c].is_active)return a.objects_stack[b][c].is_active=!0,a.objects_stack[b][c];for(var d in a.atlases){var e=a.atlases[d];for(f in e.map.frames)if(f==b){e.material.magFilter=THREE.NearestFilter;e.material.minFilter=THREE.NearestFilter;d=new THREE.PlaneGeometry(1,1);c=new THREE.MeshBasicMaterial({map:e.material,
color:16777215,transparent:!0,depthWrite:!1,side:THREE.DoubleSide});var f=e.map.frames[f];var h=c.map.image.width,g=c.map.image.height;d=new THREE.BufferGeometry;e=f.frame.x/h;var G=f.frame.y/g;h=(f.frame.x+f.frame.w)/h;g=(f.frame.y+f.frame.h)/g;e=new Float32Array([-.5,-.5,0,e,1-g,.5,-.5,0,h,1-g,.5,.5,0,h,1-G,-.5,.5,0,e,1-G]);e=new THREE.InterleavedBuffer(e,5);d.setIndex([0,1,2,0,2,3]);d.addAttribute("position",new THREE.InterleavedBufferAttribute(e,3,0,!1));d.addAttribute("uv",new THREE.InterleavedBufferAttribute(e,
2,3,!1));d=new THREE.Mesh(d,c);d.i_rw=f.frame.w;d.i_rh=f.frame.h;d.i_w=f.spriteSourceSize.w;d.r_h=f.spriteSourceSize.h;d.is_active=!0;d.free=function(){this.parent&&(this.parent.remove(this),this.is_active=!1)};a.objects_stack[b].push(d);d.p_name=b;return d}}return a.materials[b]?(c=new THREE.MeshBasicMaterial({map:a.materials[b],color:16777215,transparent:!0,depthWrite:!1,side:THREE.DoubleSide}),d=new THREE.PlaneGeometry(10,10),d=new THREE.Mesh(d,c),d.is_active=!0,d.free=function(){this.parent&&
(this.parent.remove(this),this.is_active=!1)},a.objects_stack[b].push(d),d.p_name=b,d):null};a.get_object=function(b){a.objects_stack[b]||(a.objects_stack[b]=[]);for(var c=0;c<a.objects_stack[b].length;c++)if(!a.objects_stack[b][c].is_active)return a.objects_stack[b][c].is_active=!0,a.objects_stack[b][c];for(c=0;c<a.objects.children.length;c++)if(a.objects.children[c].name==b+"_"+b+"_geom"){var d=a.objects.children[c].clone();if(Array.isArray(a.objects.children[c].material)){d.material=[];for(var e=
0;e<a.objects.children[c].material.length;e++)d.material[a.objects.children[c].material[e].name]=d.material[e]=a.objects.children[c].material[e].clone()}else d.material=a.objects.children[c].material.clone();d.material.side=THREE.DoubleSide;d.is_active=!0;d.free=function(){this.parent&&(this.parent.remove(this),this.is_active=!1)};a.objects_stack[b].push(d);d.p_name=b;return d}};a.get_fbx=function(b){var c=function(a){var b=a.clone(!0);b.animations=a.animations;b.skeleton={bones:[]};var d={};a.traverse(function(a){a.isSkinnedMesh&&
(d[a.name]=a)});var c={},e={};b.traverse(function(a){a.isBone&&(c[a.name]=a);a.isSkinnedMesh&&(e[a.name]=a)});for(var m in d){var l=d[m];a=l.skeleton;var k=e[m];k.material=[];for(var p=0;p<l.material.length;p++)k.material[l.material[p].name]=k.material[p]=l.material[p].clone();l=[];for(p=0;p<a.bones.length;p++)l.push(c[a.bones[p].name]);k.bind(new THREE.Skeleton(l,a.boneInverses));b.skeleton.bones.push(k);b.skeleton.bones.push.apply(b.skeleton.bones,$jscomp.arrayFromIterable(l));b.material=k.material}return b};
a.objects_stack[b]||(a.objects_stack[b]=[]);for(var d=0;d<a.objects_stack[b].length;d++)if(!a.objects_stack[b][d].is_active)return a.objects_stack[b][d].is_active=!0,a.objects_stack[b][d];if(a.fbx[b])return c=c(a.fbx[b]),c.mixer=new THREE.AnimationMixer(c.children[0]),c.is_active=!0,c.free=function(){this.parent&&(this.parent.remove(this),this.is_active=!1)},c.play=function(a){this.action&&this.action.stop();this.action=null;for(var b=this.animations,d=0;d<b.length;d++)if(b[d].name=="Armature|"+a){this.action=
this.mixer.clipAction(b[d]);this.action.play();break}},a.objects_stack[b].push(c),c.p_name=b,c};a.manager.onLoad=function(){if(0==a.loading_step){a.loading_step++;PROJECT.PRELOADER.show(a);for(var b in PROJECT.DAT.assets)new M(b);for(b=0;b<PROJECT.DAT.sounds.length;b++)new K(PROJECT.DAT.sounds[b]);a.font_loader.load(PROJECT.DAT.font,function(b){a.font=b});a.mtl_loader.load(PROJECT.DAT.object+".mtl"+a.ver,J);for(b=0;b<PROJECT.DAT.fbx_objects.length;b++)new L(PROJECT.DAT.fbx_objects[b])}else 1==a.loading_step&&
(a.loading_step++,a.last_time=(new Date).getTime(),PROJECT.PRELOADER.hide_bar(),O(),a.on_start())};a.sounds={};a.fbx={};a.on_texture_loaded=function(b){var c=b.image.src,d=c.search("ver");c=c.substr(0,d-1);for(d=c.length-1;0<=d;d--)if("/"==c[d]){c=c.substr(d+1,c.length-d-5);break}a.materials[c]=b};for(l=0;l<PROJECT.DAT.preloader.length;l++){var q=a.loader.load(PROJECT.DAT.gfx_folder+PROJECT.DAT.preloader[l]+".png"+a.ver,a.on_texture_loaded);q.generateMipmaps=!1;q.wrapS=q.wrapT=THREE.ClampToEdgeWrapping;
q.minFilter=THREE.LinearFilter}q=a.loader.load(PROJECT.DAT.gfx_folder+PROJECT.DAT.shadow+".png"+a.ver,a.on_texture_loaded);q.generateMipmaps=!1;q.wrapS=q.wrapT=THREE.ClampToEdgeWrapping;q.minFilter=THREE.LinearFilter;var H=function(){requestAnimationFrame(H);a.renderer.clear(!0,!0,!0);a.up_gui?(a.renderer.render(a.scene_3d,a.camera_3d),a.renderer.render(a.scene,a.camera)):(a.renderer.render(a.scene,a.camera),a.renderer.render(a.scene_3d,a.camera_3d));if(1<a.loading_step){for(var b=(new Date).getTime(),
c=0;c<a.on_update_functions.length;c++)a.on_update_functions[c](b-a.last_time);a.last_time=b}};H();a.on_resize=function(){var b=window.innerWidth||document.body.clientWidth,c=window.innerHeight||document.body.clientHeight;1>b&&(b=1);1>c&&(c=1);a.scale=c/PROJECT.DAT.height;a.dx=(b/a.scale-PROJECT.DAT.width)/2;a.dy=0;a.width=b;a.height=c;a.renderer.domElement.style.width=b+"px";a.renderer.domElement.style.height=c+"px";a.renderer.domElement.style.left="0px";a.renderer.domElement.style.top="0px";a.camera_3d.aspect=
b/c;a.camera_3d.updateProjectionMatrix();a.camera.aspect=b/c;a.camera.updateProjectionMatrix();a.renderer.setSize(b,c);a.shadow&&(a.shadow.sx=b/8/a.scale,a.shadow.x=(PROJECT.DAT.width-b/a.scale)/2);for(b=0;b<a.on_resize_functions.length;b++)a.on_resize_functions[b]()};window.addEventListener("resize",a.on_resize);window.onorientationchange=a.on_resize;a.on_resize();setTimeout(function(){window.scrollTo(0,1)},10);a.windows=[];a.current_wnd=null;a.show=function(b){for(var c=0;c<a.windows.length;c++)a.windows[c].parent&&
a.windows[c].parent.removeChild(a.windows[c]);a.current_wnd=b.copy(a.middle_gfx,!0);a.windows.push(a.current_wnd);return a.current_wnd};a.hide=function(){if(0==a.windows.length)return!1;a.current_wnd=null;a.windows.pop().free();if(0==a.windows.length)return!0;a.current_wnd=a.windows[a.windows.length-1];a.middle_gfx.addChild(a.current_wnd);return!0};a.messages=[];a.current_msg=null;a.show_msg=function(b){function c(a,b,d,c){a.alpha=b}for(var d=0;d<a.messages.length;d++)a.messages[d].parent&&a.messages[d].parent.removeChild(a.messages[d]);
for(d=0;d<a.messages.length;d++)a.msg_down_gfx.addChild(a.messages[d]);a.current_msg=b.copy(a.msg_up_gfx,!0);a.messages.push(a.current_msg);a.shadow.visible=!0;2>a.messages.length?(a.shadow.alpha=0,a.start(a.shadow,0,200,null,c)):a.shadow.alpha=1;return a.current_msg};a.hide_msg=function(){if(0==a.messages.length)return!1;a.current_msg=null;a.messages.pop().free();a.shadow.visible=0<a.messages.length;if(0==a.messages.length)return!0;for(var b=0;b<a.messages.length;b++)a.messages[b].parent&&a.messages[b].parent.removeChild(a.messages[b]);
for(b=0;b<a.messages.length-1;b++)a.msg_down_gfx.addChild(a.messages[b]);a.current_msg=a.messages[b];a.msg_up_gfx.addChild(a.current_msg);return!0};a.hide_all_msg=function(){for(;0<a.messages.length;){a.current_msg=null;a.messages.pop().free();a.shadow.visible=0<a.messages.length;if(0==a.messages.length)break;for(var b=0;b<a.messages.length;b++)a.messages[b].parent&&a.messages[b].parent.removeChild(a.messages[b]);for(b=0;b<a.messages.length-1;b++)a.msg_down_gfx.addChild(a.messages[b]);a.current_msg=
a.messages[b];a.msg_up_gfx.addChild(a.current_msg)}return!0};a.get_copy=function(b,c,d){b.copied||(b.copied=[]);for(var e=0;e<b.copied.length;e++)if(!b.copied[e].is_active)return b.copied[e].setup(c,d);if(""!=b.pic)if(0==b.col)var f=a.get_sprite(b.pic,!0);else{var h=[];for(e=0;e<b.col;e++)h.push(b.pic+"_anim_"+e);f=a.get_sprite(h,!0)}else f=a.get_sprite();b.copied.push(f);f.p=b;f.properties={};f.centered=function(){this.x=this.p_cx;this.y=this.p_cy;this.anchor.x=this.anchor.y=.5};f.setup=function(b,
d){this.visible=!0;this.alpha=this.scale.x=this.scale.y=1;this.rotation=0;this.is_active=!0;this.p_properties=this.p.properties;this.p_name=this.p.name;this.p_type=this.p.type;this.p_x=this.x=this.p.x;this.p_y=this.y=this.p.y;this.p_cx=this.p.x+this.p.w/2;this.p_cy=this.p.y+this.p.h/2;this.p_w=this.p.w;this.p_h=this.p.h;this.p_c=this.p.col;this.x=this.p_x;this.y=this.p_y;this.properties||(this.properties={});for(var c in this.p_properties)this.properties[c]=this.p_properties[c],"true"==this.properties[c]&&
(this.properties[c]=!0),"false"==this.properties[c]&&(this.properties[c]=!1);b&&(d?b.addChildDown(this):b.addChild(this));a.set_type(this,this.p_type);return this};f.setup(c,d);for(var g in b.children)f[g]=b.children[g].copy(f,!0);for(g in b.children)f[g].properties.prnt&&(c=f[g].getGlobalPosition(),f[f[g].properties.prnt].addChild(f[g]),d=f[g].getGlobalPosition(),b=c.x-d.x,c=c.y-d.y,f[g].x+=b,f[g].y+=c,f[g].p_x+=b,f[g].p_y+=c,f[g].p_cx+=b,f[g].p_cy+=c);f.free=function(){f.parent&&f.parent.removeChild(f);
f.is_active=!1;f.visible=!1};f.copy=function(b,d){return a.get_copy(this.p,b,d)};f.alarmed=!1;f.set_alarm=function(a){a?f.alarmed||(f.prev_tint=f.tint,f.tint=16711680,f.alarmed=a):f.alarmed&&(f.tint=f.prev_tint,f.alarmed=a)};return f};a.start=function(b,c,d,e,f,h,g){function l(){if(0<this.pause&&this.tk>this.life&&this.on_start)this.on_start(this.obj,this,!0);if(this.on_finish)this.on_finish(this.obj,this,!0);this.busy&&a.busy--;this.tk=0;this.is_active=!1}for(var m=0;m<k.length&&k[m].is_active;m++);
m==k.length&&k.push({obj:null,is_active:!1,tk:0,pause:0,life:0,on_start:null,on_progress:null,on_finish:null,is_busy:!1,is_working:!1,stop:l});"undefined"==typeof e&&(e=null);"undefined"==typeof f&&(f=null);"undefined"==typeof h&&(h=null);"undefined"==typeof g&&(g=!1);g&&a.busy++;k[m].obj=b;k[m].is_active=!0;k[m].tk=c+d;k[m].pause=c;k[m].life=d;k[m].on_start=e;k[m].on_progress=f;k[m].on_finish=h;k[m].is_busy=g;k[m].is_working=!1;return k[m]};a.on_update_functions.push(function(b){for(var c=0;c<k.length;c++)k[c].is_working=
k[c].is_active;for(c=0;c<k.length;c++){var d=k[c];if(d.is_working&&d.is_active){var e=0<d.pause&&d.tk>d.life,f=d.tk<b?d.tk:b;d.tk-=f;if(e&&d.tk<=d.life&&d.on_start)d.on_start(d.obj,d,!1);if(d.tk<=d.life){if(d.on_progress)d.on_progress(d.obj,(d.life-d.tk)/d.life,f,d);if(0==d.tk){if(d.on_finish)d.on_finish(d.obj,d,!1);d.is_busy&&a.busy--;d.is_active=!1}}}}});a.get_target=function(b,c,d,e,f){for(var h=b.children.length-1;0<=h;h--){var g=b.children[h];if(g.visible&&g.avk){var l=e*g.sx,m=f*g.sy,k=g.x*
e,n=g.y*f,p=a.get_target(g,c-k,d-n,l,m);if(p)return p;if(g.interactive&&c>=k&&k+g.p_w*l>c&&d>=n&&n+g.p_h*m>d)return g}}return null};a.down_object=null;a.isMobile.any()?(a.renderer.domElement.addEventListener("touchmove",E,!1),a.renderer.domElement.addEventListener("touchstart",F,!1),a.renderer.domElement.addEventListener("touchend",u,!1),a.renderer.domElement.addEventListener("touchcancel",u,!1)):(a.renderer.domElement.addEventListener("mousemove",E,!1),a.renderer.domElement.addEventListener("mousedown",
F,!1),a.renderer.domElement.addEventListener("mouseup",u,!1));a.remove_from_resize_functions=function(b){for(var c=0;c<a.on_resize_functions.length;c++)if(a.on_resize_functions[c]==b){for(b=c;b<a.on_resize_functions.length-1;b++)a.on_resize_functions[b]=a.on_resize_functions[b+1];a.on_resize_functions.pop();break}};a.convert=function(a){var b="",d=0;a=""+a;for(var e=a.length-1;0<=e;e--){3==d&&(d=0,b=" "+b);if("0"!=a.charAt(e)&&"1"!=a.charAt(e)&&"2"!=a.charAt(e)&&"3"!=a.charAt(e)&&"4"!=a.charAt(e)&&
"5"!=a.charAt(e)&&"6"!=a.charAt(e)&&"7"!=a.charAt(e)&&"8"!=a.charAt(e)&&"9"!=a.charAt(e))return a;b=a.charAt(e)+b;d++}return b};a.get_time=function(a,c){a=Math.floor(a/1E3);var b=Math.floor(a/3600);a-=3600*b;var e=Math.floor(b/24);b-=24*e;var f=Math.floor(a/60),h=""+(a-60*f),g=""+f;if(c){if(0<e)return 2>b.length&&(b="0"+b),e+PROJECT.STR.get(1E4)+b+PROJECT.STR.get(10001);if(0<b)return 2>g.length&&(g="0"+g),b+":"+g;if(0<f)return 2>h.length&&(h="0"+h),g+":"+h;2>h.length&&(h="0"+h)}else{if(0<e)return 2>
b.length&&(b="0"+b),2>h.length&&(h="0"+h),2>g.length&&(g="0"+g),e+PROJECT.STR.get(1E4)+b+":"+g+":"+h;if(0<b)return 2>h.length&&(h="0"+h),2>g.length&&(g="0"+g),b+":"+g+":"+h;if(0<f)return 2>h.length&&(h="0"+h),g+":"+h}return h};a.rad_in_rad=function(b,c,d,e,f,h){b=a.get_length(b-e,c-f);return b>d+h?-1:d+h-b};a.line_in_rad=function(b,c,d,e,f,h,g){var l=a.get_length(h-e,g-f),k=Math.abs(((f-g)*b+(h-e)*c+(e*g-h*f))/l);if(k<d){e=(e-b)*(e-b)+(f-c)*(f-c);b=(h-b)*(h-b)+(g-c)*(g-c);c=Math.sqrt(b-k*k);if(Math.sqrt(e-
k*k)<l&&c<l)return d-k;e=Math.sqrt(e);b=Math.sqrt(b);if(e<d||b<d)return d-k}return-1};a.get_length=function(a,c,d){"undefined"==typeof d&&(d=0);a=Math.sqrt(a*a+c*c+d*d);0==a&&(a=1E-7);return a};a.get_angle=function(b,c){var d=a.get_length(b,c);d=Math.acos(b/d);0>c&&(d=2*Math.PI-d);return d};a.del_array=function(a,c){for(var b=0;b<a.length;b++)if(a[b]==c){for(var e=b;e<a.length-1;e++)a[e]=a[e+1];a.pop()}};a.set_type=function(b,c){function d(a){a.interactive||(a.interactive=!0,a.avk.on_down=function(b,
c,d){b.sx=b.sy=.95;a.x=a.p_x+.05*a.p_w/2;a.y=a.p_y+.05*a.p_h/2},a.avk.on_up=a.avk.on_out=function(b,c,d){b.sx=b.sy=1;a.x=a.p_x;a.y=a.p_y})}function e(b){b.avk.txt=a.get_text(b.properties.str?PROJECT.STR.get(b.properties.str):" ",b.properties.sz?Math.floor(b.p_h/b.properties.sz):b.p_h,b.properties.tint?"#"+b.properties.tint.substr(2,6):"#ffffff");b.addChild(b.avk.txt);b.avk.img.push(b.avk.txt);b.avk.txt.position.x=b.p_w/2;b.avk.txt.position.y=b.p_h/2+(b.avk.txt.height-b.p_h)}b.objs||(b.objs={});if(!b.objs[c])switch(c){case "btn":b.objs[c]=
new d(b);break;case "txt":b.objs[c]=new e(b)}}};